"""Render the detailed contractor review from attributed observations."""
from pathlib import Path
import json,html
R=Path(__file__).resolve().parent
D=json.loads((R/'detail-review.json').read_text())
def e(x):return html.escape(str(x),quote=True)
def link(u,t):return '<a target="_blank" rel="noopener noreferrer" href="'+e(u)+'">'+e(t)+' ↗</a>'
def ul(xs):return '<ul>'+''.join('<li>'+e(x)+'</li>' for x in xs)+'</ul>'
page='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>업체가 중시하는 것과 실제 결과물 | 제주 시공사</title><link rel="stylesheet" href="style.css"><style>.review-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.review-gallery figure{margin:0}.review-gallery img{width:100%;height:300px;object-fit:contain;background:#eef1f4}.review-gallery figcaption{font-size:13px;line-height:1.7;padding:12px 0}.verdict{border-left:4px solid #226bb3;padding:16px 22px;background:#f1f6fb}.review-nav{display:flex;gap:16px;flex-wrap:wrap}@media(max-width:640px){.review-gallery{grid-template-columns:1fr}.review-gallery img{height:auto}}@media print{.review-gallery img{height:200px}section{break-before:auto}}</style></head><body><header><a class="brand" href="index.html">JEJU <b>PROPOSAL</b></a><span>결과물 정밀 검토 · 2026.09.09</span><a href="DETAIL-REVIEW.md">문서 보기</a></header><main><section class="intro"><p class="eyebrow">VALUES, WORKMANSHIP & EVIDENCE</p><h1>무엇을 중요하게 여기고,<br>어떻게 지었는가</h1><p>실제 시공업체 12곳을 대상으로, 핵심 후보의 철학·조직·완공 결과·성능 기록을 더 깊게 비교했습니다.</p><div class="notice">업체의 설명 / 직접 본 사진 / 공개 기록 / 조사자의 판단을 구분합니다. 공간 설계의 성과를 시공사 단독 성과로 돌리지 않으며, 완공 사진으로 숨은 방수·단열·구조 품질을 확정하지 않습니다.</div></section><section><h2>현재 판단</h2><p class="verdict">'''+e(D['conclusion'])+'''</p><p>가격·착공 여력은 아직 모릅니다. 세 업체를 경쟁시켜 어느 팀이 도면·공종 경계·검측·하자 책임을 가장 구체적으로 설명하는지 확인하는 것이 다음 결정 기준입니다.</p><div class="review-nav">'''+''.join('<a href="#'+p['id']+'">'+e(p['name'])+'</a>' for p in D['profiles'])+'''<a href="#others">다른 후보 8곳</a></div></section>'''
md=['# 제주 시공업체: 중요하게 여기는 것과 실제 결과물','','검토일 '+D['date'],'','## 현재 판단','',D['conclusion'],'','업체 설명·사진 관찰·공개 기록·조사자의 추론을 구분했다. 설계 성과는 설계자와, 공종 수행 범위는 실제 시공팀과 나누어 평가한다. 사진은 보이는 마감 관찰용이며 숨은 품질·하자 이력 판정용이 아니다.']
for p in D['profiles']:
 page+='<section id="'+p['id']+'"><p class="eyebrow">'+e(p['value'])+'</p><h2>'+e(p['name'])+'</h2><h3>업체가 내세우는 방향</h3><p>'+e(p['claim'])+'</p><h3>결과물·기록에서 확인한 점</h3>'+ul(p['observed'])
 if p['photos']:
  page+='<div class="review-gallery">'+''.join('<figure><a href="'+e(x['url'])+'" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="'+e(x['url'])+'" alt="'+e(x['caption'])+'"></a><figcaption>'+e(x['caption'])+'</figcaption></figure>' for x in p['photos'])+'</div>'
 page+='<h3>우리 집을 맡기는 관점의 판단</h3><p class="verdict">'+e(p['judgment'])+'</p><h3>판단을 제한하는 부분</h3><p>'+e(p['limit'])+'</p><h3>면담에서 확인할 세 가지</h3>'+ul(p['asks'])+'<p>'+ ' · '.join(link(u,t) for t,u in p['sources'])+'</p></section>'
 md+=['','## '+p['name'],'','**중심 가치: '+p['value']+'**','','업체 설명: '+p['claim'],'','### 관찰·공개 기록','']+['- '+x for x in p['observed']]+['','### 판단','',p['judgment'],'','한계: '+p['limit'],'','### 면담 질문','']+['- '+x for x in p['asks']]+['','### 근거','']+['- ['+t+']('+u+')' for t,u in p['sources']]+['- [직접 검토 사진 '+str(i+1)+']('+x['url']+') — '+x['caption'] for i,x in enumerate(p['photos'])]
page+='<section id="others"><h2>다른 후보도 같은 기준으로 판단</h2><div class="table-wrap"><table><thead><tr><th>업체</th><th>확인된 방향·단서</th><th>현재 판단</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+e(v)+'</td>' for v in row)+'</tr>' for row in D['others'])+'</tbody></table></div><p>'+ ' · '.join(link(u,t) for t,u in D['extraSources'])+'</p><p>나머지 업체의 기존 실적·지역·연락 경로는 <a href="index.html#shortlist">전체 후보 비교</a>에서 볼 수 있습니다. 확인하지 못한 업체 철학은 추측으로 작성하지 않았습니다.</p></section><section><h2>좋은 설명을 실제 약속으로 바꾸는 방법</h2><div class="table-wrap"><table><thead><tr><th>업체의 약속</th><th>받아야 할 실행 자료</th></tr></thead><tbody><tr><td>설계 의도를 지킨다</td><td>담당 소장 지정, 시공도·견본 승인, 임의 변경 방지 절차</td></tr><tr><td>고성능으로 짓는다</td><td>현장별 시험 계획·합의 기준·부적합 처리·준공 성적서</td></tr><tr><td>토목까지 통합 관리한다</td><td>성토·기초·옹벽·최종 우수처리의 책임자와 공종 범위표</td></tr><tr><td>사후 관리가 좋다</td><td>제주 보수 담당자, 실제 보수일지, 응답·출동·완료 절차</td></tr></tbody></table></div><p>사진이 마음에 드는 업체에게도, 성능 수치가 좋은 업체에게도 똑같이 요구합니다. 설계자의 기존 도서를 기준으로 짧은 기술 면담을 하고, 답변을 근거로 현장 방문 후보를 줄입니다.</p><a class="button" href="index.html#quote">견적표·평가표·문의 문안으로 이동</a></section><p class="small">이미지 12장은 공개 원문에서 직접 확인했습니다. 원본 파일은 저장소에 복제하지 않았으며 외부 제공 상태에 따라 표시되지 않을 수 있습니다. 이미지 권리는 각 원권리자에게 있습니다. 현장 방문·업체 면담·도면 전달은 하지 않았습니다.</p></main><footer>JEJU PROPOSAL · 결과물 정밀 검토</footer></body></html>'
md+=['','## 다른 후보','', '| 업체 | 확인된 방향·단서 | 현재 판단 |','|---|---|---|']+['| '+' | '.join(row)+' |' for row in D['others']]+['','## 추가 출처','']+['- ['+t+']('+u+')' for t,u in D['extraSources']]+['','다른 후보의 기존 출처는 [조사 기록](RESEARCH.md)을 참조. 이미지 원본은 저장소에 복제하지 않았다. 업체 면담·현장방문·도면 전달은 하지 않았다.']
(R/'review.html').write_text(page)
(R/'DETAIL-REVIEW.md').write_text('\n'.join(md)+'\n')
print('Built detailed review: 4 profiles, 8 follow-up assessments, 12 inspected images.')
