"""Render portfolio verification for candidates outside the original top three."""
from pathlib import Path
import json,html
R=Path(__file__).resolve().parent
D=json.loads((R/'portfolio-review.json').read_text())
def e(s):return html.escape(str(s),quote=True)
def ul(xs):return '<ul>'+''.join('<li>'+e(x)+'</li>' for x in xs)+'</ul>'
def table(headers,rows):return '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+e(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+e(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
count=sum(len(p['photos']) for p in D['profiles'])
page='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>다른 시공업체의 포트폴리오 검증 | JEJU</title><link rel="stylesheet" href="style.css"><style>.gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.gallery figure{margin:0}.gallery img{width:100%;height:320px;object-fit:contain;background:#f0f2f5}.gallery figcaption{font-size:13px;line-height:1.7;padding-top:10px}.verdict{padding:20px;border-left:4px solid #226bb3;background:#f1f6fb}.jump{display:flex;gap:16px;flex-wrap:wrap}li{line-height:1.85;margin-bottom:10px}@media(max-width:640px){.gallery{grid-template-columns:1fr}.gallery img{height:auto}}@media print{.gallery img{height:190px}}</style></head><body><header><a class="brand" href="index.html">JEJU <b>PROPOSAL</b></a><span>포트폴리오 검증 · 2026.09.09</span><a href="PORTFOLIO-REVIEW.md">문서 보기</a></header><main><section class="intro"><p class="eyebrow">BUILT WORKS · CONTRACTOR CREDITS</p><h1>포트폴리오가 확실한<br>시공업체인가</h1><p>기존 상위 3곳 외 9개 후보·협업팀을 다시 검토했습니다. 이름이 특정된 준공작, 실제 시공 역할, 외부 설계자의 확인, 제주 활동의 반복성을 봅니다.</p><div class="notice">건물 형태가 우리 설계와 같을 필요는 없습니다. 다만 실제로 맡아 완성한 범위와 이번에 배정할 팀은 확인돼야 합니다. 동일 건물의 여러 기사·단지 내 여러 동·공동 시공을 독립 실적으로 부풀리지 않았습니다.</div></section><section><h2>추가 후보 중 현재 판단</h2><p class="verdict">'''+e(D['conclusion'])+'</p>'+table(['업체','포트폴리오 근거 수준'],[[p['name'],p['level']] for p in D['profiles']])+'<div class="jump">'+''.join('<a href="#'+p['id']+'">'+e(p['name'])+'</a>' for p in D['profiles'])+'</div></section>'
md=['# 다른 제주 시공업체의 포트폴리오 검증','','검토일 '+D['date'],'',D['conclusion'],'','실제 시공 역할과 외부 설계자 자료를 중심으로 확인했다. 같은 건물의 중복 기사, 상업시설, 공사 중 기록, 공동 시공을 독립 주택 실적으로 부풀리지 않았다.','', '| 업체 | 현재 근거 수준 |','|---|---|']+['| '+p['name']+' | '+p['level']+' |' for p in D['profiles']]
for p in D['profiles']:
 page+='<section id="'+p['id']+'"><p class="eyebrow">'+e(p['level'])+'</p><h2>'+e(p['name'])+'</h2><p>'+e(p['value'])+'</p>'+table(['실적','확인 경로','확인 내용·한계'],p['works'])+'<h3>우리 집을 맡기는 관점</h3><p class="verdict">'+e(p['judgment'])+'</p><h3>확인 한계·혼동 방지</h3>'+ul(p['limits'])
 if p['photos']:page+='<div class="gallery">'+''.join('<figure><a href="'+e(q['url'])+'" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="'+e(q['url'])+'" alt="'+e(q['caption'])+'"></a><figcaption>'+e(q['caption'])+'</figcaption></figure>' for q in p['photos'])+'</div>'
 page+='<h3>원문</h3><ul>'+''.join('<li><a href="'+e(u)+'" target="_blank" rel="noopener noreferrer">'+e(t)+' ↗</a></li>' for t,u in p['sources'])+'</ul></section>'
 md+=['','## '+p['name'],'','**'+p['level']+'**','','중심 방향: '+p['value'],'','| 실적 | 확인 경로 | 내용·한계 |','|---|---|---|']+['| '+' | '.join(row)+' |' for row in p['works']]+['','### 판단','',p['judgment'],'','### 한계','']+['- '+s for s in p['limits']]+['','### 근거','']+['- ['+t+']('+u+')' for t,u in p['sources']]+['- [직접 검토 사진]('+q['url']+') — '+q['caption'] for q in p['photos']]
page+='<section><h2>포트폴리오 확인 다음의 결정</h2><p>브라운트리는 위미리·명도암의 도서와 담당팀, JD는 청수리·제라의 공종 분담, 시스홈은 제주 계약 법인과 실제 배정 소장, 이음은 구억리·하례리 설계자의 시공 확인을 우선 받으면 된다. 건축주 동의를 얻은 준공 후 거주 주택과 현재 시공 현장을 함께 볼 수 있어야 계약 판단이 가능하다.</p><p><a href="review.html">기존 주요 후보·결과물 검토</a> · <a href="index.html#shortlist">전체 후보</a> · <a href="index.html#quote">견적 비교 준비</a></p></section><p class="small">이번 직접 사진 검토 '+str(count)+'장. 이전 정밀 검토 12장과 합쳐 누적 16장이다. 외부 이미지 권리는 각 원권리자에게 있으며 원본을 저장소에 복제하지 않았다. 영상은 시청하지 않았으며 원문 접근 제한은 각 항목에 표시했다. 업체 연락·도면 전달·현장 방문은 하지 않았다.</p></main><footer>JEJU PROPOSAL · 포트폴리오 확인본</footer></body></html>'
md+=['','이번 신규 직접 사진 검토 4장, 기존 12장과 누적 16장. 원본 이미지 미복제. 업체 연락·현장 방문·도면 전달은 하지 않았다.','', '[전체 후보](index.html) · [기존 주요 후보 정밀 검토](review.html)']
(R/'portfolio.html').write_text(page);(R/'PORTFOLIO-REVIEW.md').write_text('\n'.join(md)+'\n')
print('Built 9 portfolio profiles and 4 inspected photos.')
