'use strict';
const data=JSON.parse(document.getElementById('site-data').textContent);
const $=s=>document.querySelector(s),allCards=[...document.querySelectorAll('.project')];
const dlg=$('#gallery');let company='all',project=null,index=0,lastFocus=null;
const url=new URL(location.href);if(data.companies.some(c=>c.id===url.searchParams.get('company')))company=url.searchParams.get('company');
function filter(){const term=$('#search').value.trim().toLowerCase(),kind=$('#kind').value;let count=0;for(const card of allCards){const p=data.projects.find(p=>p.id===card.dataset.project);const show=(company==='all'||p.company===company)&&(!term||(p.name+' '+p.place+' '+p.structure).toLowerCase().includes(term))&&(kind==='all'||(kind==='rc'?p.rc:p.group===kind));card.hidden=!show;if(show)count++;}document.querySelectorAll('.filters [data-company]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.company===company)));$('#result-count').textContent=count+' / '+data.projects.length+'개';$('#empty').hidden=count!==0;const u=new URL(location.href);if(company==='all')u.searchParams.delete('company');else u.searchParams.set('company',company);history.replaceState({},'',u);}
document.querySelectorAll('[data-company]').forEach(b=>b.addEventListener('click',()=>{company=b.dataset.company;filter();if(b.classList.contains('company-open'))$('#portfolio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}));$('#search').addEventListener('input',filter);$('#kind').addEventListener('change',filter);$('#reset').addEventListener('click',()=>{company='all';$('#kind').value='all';$('#search').value='';filter();});
function showPhoto(n){if(!project?.photos.length)return;index=(n+project.photos.length)%project.photos.length;const p=project.photos[index];$('#large-image').src=p.url;$('#large-image').alt=project.name+' 사진 '+(index+1);$('#gallery-title').textContent=project.name;$('#gallery-count').textContent=data.companies.find(c=>c.id===project.company).short+' · '+(index+1)+' / '+project.photos.length;$('#caption').textContent=p.caption||project.name;$('#image-credit').textContent=p.credit;$('#image-source').href=p.source||project.sources[0][1];document.querySelectorAll('#thumbs button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));document.querySelector('#thumbs [aria-pressed="true"]')?.scrollIntoView({block:'nearest',inline:'nearest'});const u=new URL(location.href);u.searchParams.set('project',project.id);u.searchParams.set('photo',index+1);history.replaceState({},'',u);if(project.photos.length>1){const preload=new Image();preload.src=project.photos[(index+1)%project.photos.length].url;}}
function openGallery(id,start=0,opener=null){project=data.projects.find(p=>p.id===id);if(!project?.photos.length)return;lastFocus=opener||document.activeElement;$('#thumbs').replaceChildren();project.photos.forEach((p,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',project.name+' 사진 '+(i+1));b.setAttribute('aria-pressed',String(i===start));const im=document.createElement('img');im.src=p.thumb;im.alt='';im.loading='lazy';b.append(im);b.addEventListener('click',()=>showPhoto(i));$('#thumbs').append(b);});dlg.showModal();document.body.classList.add('modal-open');showPhoto(start);$('#close').focus();}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openGallery(b.dataset.open,Number(b.dataset.photo||0),b)));$('#previous').addEventListener('click',()=>showPhoto(index-1));$('#next').addEventListener('click',()=>showPhoto(index+1));$('#close').addEventListener('click',()=>dlg.close());dlg.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(index-1);}if(e.key==='ArrowRight'){e.preventDefault();showPhoto(index+1);}});dlg.addEventListener('close',()=>{document.body.classList.remove('modal-open');project=null;const u=new URL(location.href);u.searchParams.delete('project');u.searchParams.delete('photo');history.replaceState({},'',u);lastFocus?.focus();});dlg.addEventListener('click',e=>{if(e.target===dlg){const r=dlg.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dlg.close();}});let touch=null;$('.stage').addEventListener('touchstart',e=>{if(e.touches.length===1)touch=[e.touches[0].clientX,e.touches[0].clientY];},{passive:true});$('.stage').addEventListener('touchend',e=>{if(!touch||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];touch=null;if(Math.abs(dx)>50&&Math.abs(dy)<70)showPhoto(index+(dx<0?1:-1));},{passive:true});
async function share(){try{if(navigator.share)await navigator.share({title:project?.name||document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);$('#toast').textContent='링크를 복사했습니다.';setTimeout(()=>$('#toast').textContent='',3000);}}catch(e){if(e.name!=='AbortError')window.prompt('이 주소를 복사해 주세요.',location.href);}}
$('#share').addEventListener('click',share);$('#share-project').addEventListener('click',share);$('#print').addEventListener('click',()=>window.print());filter();if(url.searchParams.has('project'))openGallery(url.searchParams.get('project'),Math.max(0,(Number(url.searchParams.get('photo'))||1)-1));document.documentElement.dataset.ready='true';
