import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {load} from 'cheerio';import sharp from 'sharp';
const OUT='site-v3/published';await fs.mkdir(OUT+'/assets',{recursive:true});sharp.concurrency(1);sharp.cache({memory:32,items:20});
const read=async f=>JSON.parse(await fs.readFile(f,'utf8'));const [base,ext,ranks]=await Promise.all(['portfolio-data.json','portfolio-expansion.json','ranking.json'].map(read));
const order=['ia','gau','dabom'];let companies=[...base.companies,...ext.companies].filter((c,i,a)=>order.includes(c.id)&&a.findIndex(x=>x.id===c.id)===i).sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
let projects=[...base.projects,...ext.projects].filter(p=>order.includes(p.company)).map(p=>structuredClone(p));for(const p of projects){const patch=ext.projectPatches[p.id];if(patch){const {extraSources,...rest}=patch;Object.assign(p,rest);if(extraSources)p.sources=[...p.sources,...extraSources];}p.photos=p.photos||[];p.group=/스테이/.test(p.kind)?'stay':/복합|티룸|사무실/.test(p.kind)?'mixed':'house';}
for(const c of companies){const r=ranks.candidates.find(x=>x.id===c.id);if(r){c.score=r.total;c.rank=r.rank;c.points=r.points;}}
const yf=projects.find(p=>p.id==='yeongpyeong');Object.assign(yf,{kind:'단독주택·근린생활시설',group:'mixed',structure:'지상 2층 · 본체 구조 별도 확인',designer:'포머티브 건축사사무소',period:'시공 2022.02–2023.04 · 업체 표기',area:'공식 면적: 주택 134.52㎡ / 근린생활시설 65.42㎡ · 필드 불일치 주의',caution:'업체 페이지는 단독주택과 근린생활시설을 함께 표기합니다. 면적 필드가 서로 일치하지 않아 합계나 순수 단독주택 규모로 단정하지 않습니다. 사진은 업체 공개 완공 사례입니다.'});
const SPEC={
 solbinamujip:['https://www.arootarchitecture.com/보성리솔비나무집','wix'],hwabun:['https://iacompany.co.kr/projects/hwabun/','ia'],yeonanjae:['https://vmspace.com/project/project_view.html?base_seq=MzI5MA%3D%3D','space'],jaejaesoso:['https://iacompany.co.kr/projects/jaejaesoso/','ia'],eoheung:['https://iacompany.co.kr/projects/eoeum/','ia'],yeongpyeong:['https://iacompany.co.kr/projects/Yeongpyeongdong-house/','ia'],homi:['https://vmspace.com/project/project_view.html?base_seq=MzAzMg%3D%3D','space'],hacheon:['https://vmspace.com/project/project_view.html?base_seq=MjgzNg%3D%3D','space'],got:['https://www.kim-o.kr/portfolio-collections/works/gotjawal-house','wix'],hangsimdang:['https://www.arootarchitecture.com/남원주택','wix'],woljeong:['https://v.daum.net/v/W0Da5xsdFN','daum'],ora:['https://www.masterbuilder.kr/portfolio/oradong-hyeonine','masterbuilder'],jeoji:['https://www.arootarchitecture.com/저지오름아래','wix'],simyang:['https://www.arootarchitecture.com/p2018용담심양재','wix'],haean:['https://vmspace.com/project/project_view.html?base_seq=MjgzNw%3D%3D','space'],sowon:['https://www.arootarchitecture.com/과수원집소원재','wix'],little:['https://www.arootarchitecture.com/제주작은집','wix']};
const HOSTS=new Set(['iacompany.co.kr','www.iacompany.co.kr','www.arootarchitecture.com','arootarchitecture.com','static.wixstatic.com','www.kim-o.kr','vmspace.com','www.vmspace.com','v.daum.net','t1.daumcdn.net','www.masterbuilder.kr','masterbuilder.kr','www.gauaf.com','gauaf.com','images.squarespace-cdn.com','cdn.prod.website-files.com','uploads-ssl.webflow.com','lh3.googleusercontent.com','storage.googleapis.com']);
const manifest={version:'static-v3',sourceCommit:process.env.GITHUB_SHA||null,builtAt:new Date().toISOString(),excluded:{id:'atelier',reason:'공동체·협동조합 주택 위주의 현재 검토 실적을 이번 개별 단독주택 메인 비교에서 제외. 원자료 보존.'},projects:[],failures:[],files:[]};
async function get(address,limit=32*1024*1024){let u=new URL(address);for(let hop=0;hop<4;hop++){if(u.protocol!=='https:'||!HOSTS.has(u.hostname))throw Error('Unapproved origin '+u.hostname);const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(r.status>=300&&r.status<400){const to=r.headers.get('location');await r.body?.cancel();if(!to)throw Error('No redirect');u=new URL(to,u);continue;}if(!r.ok){await r.body?.cancel();throw Error('HTTP '+r.status);}if(Number(r.headers.get('content-length')||0)>limit){await r.body?.cancel();throw Error('Source size limit');}const chunks=[];let n=0;for await(const c of r.body){n+=c.length;if(n>limit)throw Error('Source size limit');chunks.push(c);}return Buffer.concat(chunks);}throw Error('Redirect limit');}
function canonical(s){try{const u=new URL(s);if(u.hostname==='static.wixstatic.com'){const m=u.pathname.match(/\/media\/([^/]+)/);if(m)return 'https://static.wixstatic.com/media/'+m[1];}u.search='';return u.href;}catch{return s;}}
function imagesFrom(html,address,mode){const $=load(html);let items=[];if(mode==='wix'){for(const m of html.matchAll(/"mediaUrl"\s*:\s*"([^"\\]+\.(?:jpg|jpeg|png))"/gi))items.push('https://static.wixstatic.com/media/'+m[1]);if(!items.length)$('img[src*="static.wixstatic.com/media/"]').each((_,e)=>{const s=$(e).attr('src');if(!/logo|monogram/i.test(s+' '+$(e).attr('alt')))items.push(s);});}else if(mode==='ia'){$('img[src*="/image/project/"]').each((_,e)=>items.push(new URL($(e).attr('src'),address).href));}else if(mode==='space'){$('img[src*="/board_img/"]').each((_,e)=>items.push(new URL($(e).attr('src'),address).href));}else if(mode==='daum'){$('img').each((_,e)=>{const s=$(e).attr('src')||$(e).attr('data-src');if(s&&/t1.daumcdn.net\/news\//.test(s))items.push(s);});}else if(mode==='masterbuilder'){const galleries=$('[class*="gallery"], [class*="Gallery"], [class*="slider"]');galleries.find('img').each((_,e)=>{const s=$(e).attr('src');if(s)items.push(new URL(s,address).href);});}return [...new Set(items.map(canonical))].slice(0,48);}
const oldHtml=await fs.readFile('contractor-gallery.html','utf8');const embedded=[...oldHtml.matchAll(/src\s*=\s*(["'])(data:image\/(?:jpeg|jpg|png|webp);base64,[A-Za-z0-9+/=\s]+)\1/gi)].map(m=>Buffer.from(m[2].slice(m[2].indexOf(',')+1),'base64'));
async function limited(list,n,fn){const result=new Array(list.length);let at=0;await Promise.all(Array.from({length:Math.min(n,list.length)},async()=>{while(at<list.length){const i=at++;result[i]=await fn(list[i],i);}}));return result;}
async function save(p,item,i){const bytes=Number.isInteger(item.galleryIndex)?embedded[item.galleryIndex]:await get(item.url);if(!bytes)throw Error('Archived image missing');const meta=await sharp(bytes,{limitInputPixels:64000000}).metadata();if((meta.width||0)<400||(meta.height||0)<260)throw Error('Excluded small graphic');const image=await sharp(bytes,{limitInputPixels:64000000}).rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:84}).toBuffer();const hash=createHash('sha256').update(image).digest('hex').slice(0,18);const name=p.id+'-'+hash;const thumb=await sharp(image).resize({width:480,height:360,fit:'cover'}).webp({quality:77}).toBuffer();await fs.writeFile(OUT+'/assets/'+name+'.webp',image);await fs.writeFile(OUT+'/assets/'+name+'-thumb.webp',thumb);const result={url:'./assets/'+name+'.webp',thumb:'./assets/'+name+'-thumb.webp',caption:item.caption||p.name+' · 원문 공개 이미지 '+(i+1),credit:item.credit,source:item.source||p.sources[0][1],sourceImage:item.url||'repository:contractor-gallery.html#'+item.galleryIndex,width:meta.width,height:meta.height,bytes:image.length,hash};manifest.files.push({project:p.id,...result});return result;}
await limited(projects,3,async p=>{const [source,mode]=SPEC[p.id];const seeds=p.photos.map(x=>({...x,source:p.sources[0][1]}));let discovered=[];try{const html=(await get(source,4*1024*1024)).toString('utf8');const $=load(html);const title=$('title').text();if(!/403|not found|404|Access Denied/i.test(title)){discovered=imagesFrom(html,source,mode).map(url=>({url,source,credit:mode==='ia'?'이미지 출처 이아컴퍼니 · 설계 '+p.designer+' · 사진가 원문 미표기':seeds[0]?.credit||('이미지 출처 '+new URL(source).hostname+' · 사진가 별도 확인')}));}manifest.projects.push({id:p.id,name:p.name,source,title,discovered:discovered.length});}catch(e){manifest.failures.push({project:p.id,stage:'page',source,reason:e.message});manifest.projects.push({id:p.id,name:p.name,source,discovered:0});}
let photos=(await limited(discovered,2,async(item,i)=>{try{return await save(p,item,i);}catch(e){manifest.failures.push({project:p.id,stage:'image',source:item.url,reason:e.message});return null;}})).filter(Boolean);
if(photos.length<Math.max(1,seeds.length)){const fallback=(await limited(seeds,2,async(item,i)=>{try{return await save(p,item,i);}catch(e){manifest.failures.push({project:p.id,stage:'fallback',source:item.url||item.galleryIndex,reason:e.message});return null;}})).filter(Boolean);photos=[...photos,...fallback];}
p.photos=photos.filter((x,i,a)=>a.findIndex(z=>z.hash===x.hash)===i);p.sourceGallery=source;const rec=manifest.projects.find(x=>x.id===p.id);rec.saved=p.photos.length;console.log('GALLERY '+JSON.stringify({id:p.id,discovered:discovered.length,saved:p.photos.length}));});
for(const c of companies){c.projects=projects.filter(p=>p.company===c.id).length;c.photoCount=projects.filter(p=>p.company===c.id).reduce((n,p)=>n+p.photos.length,0);}
const data={version:'static-v3',builtAt:manifest.builtAt,companies,projects};manifest.totalProjects=projects.length;manifest.totalImages=projects.reduce((n,p)=>n+p.photos.length,0);manifest.missing=projects.filter(p=>!p.photos.length).map(p=>({id:p.id,name:p.name}));manifest.delivery='All published images are local static files; no visitor-time proxy or image conversion.';
const used=new Set(projects.flatMap(p=>p.photos.flatMap(x=>[path.basename(x.url),path.basename(x.thumb)])));for(const file of await fs.readdir(OUT+'/assets'))if(!used.has(file))await fs.unlink(OUT+'/assets/'+file);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const link=(name,url)=>'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(name)+' ↗</a>';
const cover=p=>p.photos[0];const companyHtml=companies.map(c=>{const p=projects.find(p=>p.id===c.hero&&p.photos.length)||projects.find(p=>p.company===c.id&&p.photos.length);return '<article class="company"><img class="company-cover" src="'+esc(cover(p).url)+'" alt="'+esc(p.name)+'" loading="eager" decoding="async"><div class="company-body"><h2>'+esc(c.short)+'</h2><p>'+esc(c.tagline)+'</p><div class="company-stats">'+c.projects+'개 프로젝트 · '+c.photoCount+'개 이미지</div><button type="button" class="company-open" data-company="'+c.id+'">프로젝트 보기 →</button></div></article>';}).join('');
const cards=projects.map(p=>{const c=companies.find(c=>c.id===p.company);const gallery=p.photos.length?'<button type="button" class="project-cover" data-open="'+p.id+'" aria-label="'+esc(p.name)+' 사진 확대"><img src="'+cover(p).url+'" alt="'+esc(p.name)+'" loading="lazy" decoding="async"><span>'+p.photos.length+'개 이미지 · 확대 ＋</span></button><div class="photo-strip">'+p.photos.slice(0,5).map((x,i)=>'<button type="button" data-open="'+p.id+'" data-photo="'+i+'" aria-label="'+esc(p.name)+' 사진 '+(i+1)+'"><img src="'+x.thumb+'" alt="" loading="lazy" decoding="async"></button>').join('')+(p.photos.length>5?'<button type="button" class="more" data-open="'+p.id+'" data-photo="5">+'+(p.photos.length-5)+'</button>':'')+'</div>':'<div class="no-image"><b>사진 확보 중</b><p>다른 프로젝트 사진으로 대신하지 않았습니다.</p>'+link('공식 원문',p.sources[0][1])+'</div>';return '<article class="project" data-project="'+p.id+'">'+gallery+'<div class="project-body"><div class="tags"><span class="tag">'+esc(c.short)+'</span><span class="tag kind">'+esc(p.kind)+'</span></div><h3>'+esc(p.name)+'</h3><p class="meta">'+esc(p.place)+'<br>'+esc(p.structure)+'</p><p class="focus">'+esc(p.focus)+'</p><details><summary>규모·출처·확인할 점 ▾</summary><p><b>규모</b> '+esc(p.area)+'<br><b>기간</b> '+esc(p.period)+'<br><b>설계</b> '+esc(p.designer)+'<br><b>시공 역할</b> '+esc(p.credit)+'</p><p>'+esc(p.caution)+'</p>'+p.sources.map(s=>link(s[0],s[1])).join(' ')+'</details><p class="credit">'+esc(cover(p)?.credit||'공식 사진을 확보하지 못했습니다.')+'</p></div></article>';}).join('');
const compare=companies.map(c=>'<article class="comparison"><h3>'+esc(c.short)+'</h3><b>비교할 근거</b><p>'+esc(c.strength)+'</p><b>계약 전 확인</b><p>'+esc(c.pending)+'</p><p class="question">'+esc(c.question)+'</p><p class="muted">기존 공개근거 점수 '+c.score+'/100 · 계약 적격 판정 아님</p></article>').join('');
let html=await fs.readFile('site-v3/template.html','utf8');const replacements={'__SUMMARY__':projects.length+'개 프로젝트 · '+manifest.totalImages+'개 저장 이미지 · 외부 사이트 이동 없이 보기','__COMPANIES__':companyHtml,'__CARDS__':cards,'__COMPARE__':compare,'__DATA__':JSON.stringify(data).replace(/</g,'\\u003c'),'__DATE__':'2026.09.15'};for(const [k,v] of Object.entries(replacements))html=html.replace(k,v);await fs.writeFile(OUT+'/index.html',html);await fs.writeFile(OUT+'/catalog.json',JSON.stringify(data,null,2));await fs.writeFile(OUT+'/image-manifest.json',JSON.stringify(manifest,null,2));await fs.copyFile('site-v3/app.js',OUT+'/app.js');await fs.copyFile('site-v3/style.css',OUT+'/style.css');await fs.writeFile(OUT+'/robots.txt','User-agent: *\nDisallow: /\n');await fs.writeFile(OUT+'/.nojekyll','');console.log('STATIC_SUMMARY '+JSON.stringify({projects:manifest.totalProjects,images:manifest.totalImages,missing:manifest.missing,companies:companies.map(c=>({name:c.short,projects:c.projects,images:c.photoCount})),failedSources:manifest.failures.length}));if(projects.length!==17||companies.length!==3||manifest.totalImages<35)throw Error('Incomplete static gallery; deployment not approved');
